# Generated by Django 5.2.8 on 2025-12-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_product_description_product_is_active_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS core_orderitem (
                id BIGSERIAL PRIMARY KEY,
                order_id BIGINT NOT NULL REFERENCES core_order (id),
                product_id BIGINT NOT NULL REFERENCES core_product (id),
                quantity_kg NUMERIC(5,1) NOT NULL,
                price_per_kg NUMERIC(6,2) NOT NULL,
                subtotal NUMERIC(10,2) NOT NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS core_orderitem;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS core_cartitem (
                id BIGSERIAL PRIMARY KEY,
                cart_id BIGINT NOT NULL REFERENCES core_cart (id),
                product_id BIGINT NOT NULL REFERENCES core_product (id),
                quantity_kg NUMERIC(5,1) NOT NULL,
                CONSTRAINT core_cartitem_cart_id_product_id_unique UNIQUE (cart_id, product_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS core_cartitem;"
        ),
    ]